//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAlCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAraclar
    {
        public byte Arabaid { get; set; }
        public Nullable<byte> Kullaniciid { get; set; }
        public string Vasita { get; set; }
        public string Yil { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public string AracDurumu { get; set; }
        public Nullable<int> KM { get; set; }
        public string KasaTipi { get; set; }
        public string MotorGücü { get; set; }
        public string MotorHacmi { get; set; }
        public string Cekis { get; set; }
        public string Renk { get; set; }
        public string Kimden { get; set; }
    }
}
