//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAlCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanicilar
    {
        public byte Kullaniciid { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public Nullable<System.DateTime> KullaniciDogumTarih { get; set; }
        public string KullaniciEPosta { get; set; }
        public string KullaniciSifre { get; set; }
        public string KullaniciCinsiyet { get; set; }
    }
}
